BRS:325 - Implements FAQ for DUP admin
bcgov/parks-reso-admin pull request #332
Opened 2024-01-16 23:49 UTC by Christopher-walsh22

### Jira Ticket:
BRS-325

### Jira Ticket URL:
[Ticket 325](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47055544)

### Description:
Adds FAQ to sidebar if a user is sysadmin
Allows users to access FAQ page if user is a sysadmin
On FAQ page Load retrieves FAQ data to be displayed in WYSIWYG
WYSIWYG edits contents of FAQ data stored in db
Toast notification on success or failure of editing FAQ
Buttons to match Edit park WYSIWYG

2024-01-17 22:21 UTC, meredithom requested changes
Will review again once the issue we discussed with the rest button is sorted out! 
Also small nit to remove unnecessary console logs.

2024-01-17 23:09 UTC, Christopher-walsh22 commented on src/app/app-routing.module.ts
> +      icon: 'bi-bar-chart',
Addressed in: [Commit](https://github.com/bcgov/parks-reso-admin/pull/332/commits/87a1429390e10ee909de0b551118a4d29694f51f)

2024-01-17 23:16 UTC, Christopher-walsh22 commented
@meredithom After our talk about the reset button I reached out to @ndelraye and received confirmation the reset button was not needed. I have removed that functionality as well as the console logging you have mentioned. Should be good for re-review now :)

2024-01-18 00:39 UTC, meredithom approved these changes

2024-01-18 17:56 UTC, marklise approved these changes
👍 merge when API side is all ready

2024-01-22 16:55 UTC, merged

2024-11-01 17:00 UTC, LindsayMacfarlane commented
Development ticket associated with this PR still open, so leaving PR open.

2024-12-05 21:27 UTC, manuji commented
Closing the PR as this work has been already completed and deployed to PROD.